"$schema" = 'https://starship.rs/config-schema.json'

command_timeout = 3000

format = """
[ÓÇ∂](color_orange)\
[üß†Ô∏è](color_fg0 bg:color_orange)\
$username\
[ÓÇ∞](bg:color_yellow fg:color_orange)\
$directory\
[ÓÇ∞](fg:color_yellow bg:color_aqua)\
$git_branch\
$git_status\
$git_commit\
[ÓÇ∞](fg:color_aqua bg:color_blue)\
$golang\
$nodejs\
$java\
$kotlin\
$python\
[ÓÇ∞](fg:color_blue bg:color_bg3)\
$docker_context\
[ÓÇ∞](fg:color_bg3 bg:color_bg1)\
$time\
$cmd_duration\
[ÓÇ¥ ](fg:color_bg1)\
$line_break$character"""

palette = 'gruvbox_dark'

[palettes.gruvbox_dark]
color_aqua = '#689d6a'
color_bg1 = '#3c3836'
color_bg3 = '#665c54'
color_blue = '#458588'
color_fg0 = '#fbf1c7'
color_green = '#98971a'
color_orange = '#d65d0e'
color_purple = '#b16286'
color_red = '#cc241d'
color_yellow = '#d79921'

[os]
disabled = true
style = "bg:color_red fg:color_fg0"

[os.symbols]
Alpine = "ÔåÄ"
Amazon = "Ôâ∞"
Android = "Óúé"
Arch = "Û∞£á"
Artix = "ÔøΩ"
CentOS = "ÔåÑ"
Debian = "Û∞£ö"
Fedora = "Û∞£õ"
Gentoo = "Û∞£®"
Linux = "Û∞åΩ"
Macos = "Û∞Äµ"
Manjaro = "Ôåí"
Mint = "ÔøΩ"
Raspbian = "Û∞êø"
RedHatEnterprise = "Û±Ñõ"
Redhat = "Û±Ñõ"
SUSE = "Ôåî"
Ubuntu = "Û∞ïà"
Windows = "Û∞ç≤"

[username]
format = '[ $user ]($style)'
show_always = true
style_root = "bg:color_orange fg:color_fg0"
style_user = "bg:color_orange fg:color_fg0"

[directory]
format = "[ $path ]($style)"
style = "fg:color_fg0 bg:color_yellow"
truncate_to_repo = false
truncation_length = 3
truncation_symbol = "‚Ä¶/"

[fill]
style = 'bold green'
symbol = '-'

[directory.substitutions]
"Documents" = "Û∞àô "
"Downloads" = "ÔÄô "
"Music" = "Û∞ùö "
"Pictures" = "ÔÄæ "

[git_branch]
format = '[[ $symbol $branch ](fg:color_fg0 bg:color_aqua)]($style)'
style = "bg:color_aqua"
symbol = "Ôäñ Ôêò"

[git_status]
format = '[[($all_status$ahead_behind )](fg:color_fg0 bg:color_aqua)]($style)'
style = "bg:color_aqua"

[git_commit]
format = '[[$hash $tag](fg:color_fg0 bg:color_aqua)]($style)'
only_detached = false
style = "bg:color_aqua"

[nodejs]
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'
style = "bg:color_blue"
symbol = "Óúò"

[c]
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'
style = "bg:color_blue"
symbol = "Óòû "

[rust]
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'
style = "bg:color_blue"
symbol = "Óû®"

[golang]
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'
style = "bg:color_blue"
symbol = "Óòß"

[php]
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'
style = "bg:color_blue"
symbol = "Óòà"

[java]
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'
style = "bg:color_blue"
symbol = "Óâñ "

[kotlin]
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'
style = "bg:color_blue"
symbol = "Óò¥"

[haskell]
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'
style = "bg:color_blue"
symbol = "Óòü"

[python]
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'
style = "bg:color_blue"
symbol = "ÓòÜ"

[docker_context]
format = '[[ $symbol( $context) ](fg:#83a598 bg:color_bg3)]($style)'
style = "bg:color_bg3"
symbol = "Ôåà"

[conda]
format = '[[ $symbol( $environment) ](fg:#83a598 bg:color_bg3)]($style)'
style = "bg:color_bg3"

[time]
disabled = false
format = '[[ Ôê∫ $time ](fg:color_fg0 bg:color_bg1)]($style)'
style = "bg:color_bg1"
time_format = "%R"

[cmd_duration]
format = '[Ôâí $duration](bold fg:color_yellow bg:color_bg1)($style)'
min_time = 500

[line_break]
disabled = false

[character]
disabled = false
error_symbol = '[ Óºµ ](bold fg:color_red)'
success_symbol = '[ ÔÑÅ ](bold fg:color_green)'
vimcmd_replace_one_symbol = '[Ôê¥](bold fg:color_purple)'
vimcmd_replace_symbol = '[Ôê¥](bold fg:color_purple)'
vimcmd_symbol = '[Ôê¥](bold fg:color_green)'
vimcmd_visual_symbol = '[Ôê¥](bold fg:color_yellow)'
